### ISSUE TITLE
Add I2C General Call Commands

### ISSUE THREAD

**Issue by codenio** [adafruit/Adafruit_CircuitPython_MCP4728#9]
we could add the following I2C General Call Commands, to enhance the features of this library
- General Call Reset
- General Call Wake-Up
- General Call Software Update
- General Call Read Address Bits

**Comment by jposada202020** [comment]
Hello, we always are open for contributions, let me know if you want to submit a PR. Thanks @codenio

**Comment by codenio** [comment]
yes @jposada202020 , I could submit a PR on the same, let me try
